export const POST_REQUEST = "POST_REQUEST";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAILURE = "POST_FAILURE";
export const POST_RESET = "POST_RESET";

export const TIMELINE_POST_REQUEST = "TIMELINE_POST_REQUEST";
export const TIMELINE_POST_SUCCESS = "TIMELINE_POST_SUCCESS";
export const TIMELINE_POST_FAILURE = "TIMELINE_POST_FAILURE";
export const TIMELINE_POST_RESET = "TIMELINE_POST_RESET";
